CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_account_status
        CHECK (account_status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uq_users_email_lower
    ON users (LOWER(email));


CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL DEFAULT 'Personal Wallet',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_wallets_user_id UNIQUE (user_id),

    CONSTRAINT fk_wallets_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);


CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(50) NOT NULL,
    category_type VARCHAR(20) NOT NULL,
    icon_key VARCHAR(50) NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_categories_type
        CHECK (category_type IN ('INCOME', 'EXPENSE')),

    CONSTRAINT chk_categories_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED')),

    CONSTRAINT chk_categories_ownership
        CHECK (
            (is_system = TRUE AND user_id IS NULL)
            OR
            (is_system = FALSE AND user_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_custom_category_name_type
    ON categories (user_id, category_type, LOWER(name))
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX uq_system_category_name_type
    ON categories (category_type, LOWER(name))
    WHERE user_id IS NULL;


CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    description VARCHAR(255),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transactions_wallet
        FOREIGN KEY (wallet_id)
        REFERENCES wallets (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transactions_type
        CHECK (transaction_type IN ('INCOME', 'EXPENSE')),

    CONSTRAINT chk_transactions_amount
        CHECK (amount > 0)
);

CREATE INDEX idx_transactions_wallet
    ON transactions (wallet_id);

CREATE INDEX idx_transactions_category
    ON transactions (category_id);

CREATE INDEX idx_transactions_occurred_at
    ON transactions (occurred_at);


CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    limit_amount NUMERIC(19, 2) NOT NULL,
    budget_month DATE NOT NULL,
    note VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_budgets_wallet
        FOREIGN KEY (wallet_id)
        REFERENCES wallets (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_budgets_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_budget_wallet_category_month
        UNIQUE (wallet_id, category_id, budget_month),

    CONSTRAINT chk_budgets_limit_amount
        CHECK (limit_amount > 0),

    CONSTRAINT chk_budgets_first_day
        CHECK (EXTRACT(DAY FROM budget_month) = 1)
);

CREATE INDEX idx_budgets_wallet
    ON budgets (wallet_id);

CREATE INDEX idx_budgets_category
    ON budgets (category_id);

CREATE INDEX idx_budgets_month
    ON budgets (budget_month);


CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    hide_balance_by_default BOOLEAN NOT NULL DEFAULT FALSE,
    compact_transaction_list BOOLEAN NOT NULL DEFAULT FALSE,
    show_budget_warnings BOOLEAN NOT NULL DEFAULT TRUE,
    budget_warning_threshold INTEGER NOT NULL DEFAULT 70,
    date_format VARCHAR(20) NOT NULL DEFAULT 'DD/MM/YYYY',
    dashboard_period VARCHAR(30) NOT NULL DEFAULT 'CURRENT_MONTH',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_user_preferences_user_id
        UNIQUE (user_id),

    CONSTRAINT fk_user_preferences_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_preferences_warning_threshold
        CHECK (budget_warning_threshold IN (70, 80, 90)),

    CONSTRAINT chk_preferences_date_format
        CHECK (
            date_format IN (
                'DD/MM/YYYY',
                'MM/DD/YYYY',
                'YYYY-MM-DD'
            )
        ),

    CONSTRAINT chk_preferences_dashboard_period
        CHECK (
            dashboard_period IN (
                'CURRENT_MONTH',
                'LAST_30_DAYS'
            )
        )
);


CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_refresh_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);