-- Add email verification state to users.

ALTER TABLE users
    DROP CONSTRAINT chk_users_account_status;

ALTER TABLE users
    ALTER COLUMN account_status
    SET DEFAULT 'PENDING_VERIFICATION';

ALTER TABLE users
    ADD COLUMN email_verified_at TIMESTAMP;

-- Existing ACTIVE development users were created before
-- email verification was introduced, so they remain usable.

UPDATE users
SET email_verified_at = created_at
WHERE account_status = 'ACTIVE'
  AND email_verified_at IS NULL;

ALTER TABLE users
    ADD CONSTRAINT chk_users_account_status
    CHECK (
        account_status IN (
            'PENDING_VERIFICATION',
            'ACTIVE',
            'DISABLED'
        )
    );

-- Temporary security codes for email verification
-- and password reset operations.

CREATE TABLE email_action_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    purpose VARCHAR(30) NOT NULL,

    code_hash VARCHAR(255) NOT NULL,

    expires_at TIMESTAMP NOT NULL,

    resend_available_at TIMESTAMP NOT NULL,

    failed_attempts INTEGER NOT NULL DEFAULT 0,

    verified_at TIMESTAMP,

    action_token_hash VARCHAR(255),

    action_token_expires_at TIMESTAMP,

    invalidated_at TIMESTAMP,

    used_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_email_action_codes_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_email_action_codes_purpose
        CHECK (
            purpose IN (
                'EMAIL_VERIFICATION',
                'PASSWORD_RESET'
            )
        ),

    CONSTRAINT chk_email_action_codes_failed_attempts
        CHECK (failed_attempts >= 0)
);

CREATE UNIQUE INDEX uq_email_action_codes_action_token_hash
    ON email_action_codes (action_token_hash)
    WHERE action_token_hash IS NOT NULL;

CREATE INDEX idx_email_action_codes_user_purpose_created
    ON email_action_codes (user_id, purpose, created_at DESC);

CREATE INDEX idx_email_action_codes_user_purpose_expiry
    ON email_action_codes (user_id, purpose, expires_at);

CREATE INDEX idx_email_action_codes_expires_at
    ON email_action_codes (expires_at);