ALTER TABLE budgets
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE budgets
    DROP CONSTRAINT IF EXISTS uq_budget_wallet_category_month;

ALTER TABLE budgets
    ADD CONSTRAINT chk_budgets_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'));

CREATE UNIQUE INDEX uq_active_budget_wallet_category_month
    ON budgets (wallet_id, category_id, budget_month)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_budgets_wallet_month_status
    ON budgets (wallet_id, budget_month, status);

CREATE TABLE planned_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    due_on DATE NOT NULL,
    recurrence VARCHAR(20) NOT NULL DEFAULT 'NONE',
    status VARCHAR(20) NOT NULL DEFAULT 'UPCOMING',
    note VARCHAR(255),
    create_client_request_id UUID NOT NULL,
    paid_on DATE,
    paid_transaction_id BIGINT,
    payment_client_request_id UUID,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_planned_expenses_wallet
        FOREIGN KEY (wallet_id)
        REFERENCES wallets (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_planned_expenses_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_planned_expenses_transaction
        FOREIGN KEY (paid_transaction_id)
        REFERENCES transactions (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_planned_expenses_amount
        CHECK (amount > 0),

    CONSTRAINT chk_planned_expenses_recurrence
        CHECK (recurrence IN ('NONE', 'WEEKLY', 'MONTHLY', 'YEARLY')),

    CONSTRAINT chk_planned_expenses_status
        CHECK (status IN ('UPCOMING', 'PAID', 'CANCELLED', 'ARCHIVED')),

    CONSTRAINT chk_planned_expenses_payment_state
        CHECK (
            (status = 'PAID'
                AND paid_on IS NOT NULL
                AND paid_transaction_id IS NOT NULL
                AND payment_client_request_id IS NOT NULL)
            OR
            (status <> 'PAID'
                AND paid_on IS NULL
                AND paid_transaction_id IS NULL
                AND payment_client_request_id IS NULL)
        )
);

CREATE UNIQUE INDEX uq_planned_expenses_create_request
    ON planned_expenses (wallet_id, create_client_request_id);

CREATE INDEX idx_planned_expenses_wallet_status_due
    ON planned_expenses (wallet_id, status, due_on, id);

CREATE INDEX idx_planned_expenses_category
    ON planned_expenses (category_id);

CREATE UNIQUE INDEX uq_planned_expenses_payment_request
    ON planned_expenses (wallet_id, payment_client_request_id)
    WHERE payment_client_request_id IS NOT NULL;
