spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-expiration-minutes=30
security.jwt.refresh-token-expiration-days=30