import 'package:flutter/material.dart';
import '../../../../core/constants/app_spacing.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../categories/presentation/widgets/category_icon.dart';
import '../../../profile/data/models/user_preferences_model.dart';
import '../../../transactions/utils/transaction_formatters.dart';
import '../../data/models/planned_expense_model.dart';
class PlannedExpenseCard extends StatelessWidget{const PlannedExpenseCard({required this.item,required this.dateFormat,required this.onTap,super.key});final PlannedExpenseModel item;final DateFormatPreference dateFormat;final VoidCallback onTap;@override Widget build(BuildContext context){final Color accent=item.status==PlannedExpenseStatus.paid?AppColors.accent:item.status==PlannedExpenseStatus.cancelled?AppColors.disabled:AppColors.error;final String date=TransactionFormatters.formatDate(item.dueOn,dateFormat);return Material(color:AppColors.surface,borderRadius:BorderRadius.circular(18),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(AppSpacing.md),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:accent.withValues(alpha:.1),borderRadius:BorderRadius.circular(14)),child:Icon(CategoryIcon.fromKey(item.category.iconKey),color:accent)),const SizedBox(width:AppSpacing.md),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.title,maxLines:1,overflow:TextOverflow.ellipsis,style:AppTextStyles.body.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:2),Text('${item.category.name} · $date',maxLines:1,overflow:TextOverflow.ellipsis,style:AppTextStyles.helperText)])),const SizedBox(width:AppSpacing.sm),ConstrainedBox(constraints:const BoxConstraints(maxWidth:130),child:FittedBox(fit:BoxFit.scaleDown,child:Text(TransactionFormatters.formatCurrencyAmount(context:context,currencyCode:item.currencyCode,amount:item.amount),style:AppTextStyles.body.copyWith(color:accent,fontWeight:FontWeight.w800))))]))));}}
